import { ContributionDay } from "../utils/contribution-calendar.util";

/**
 * A single dated activity shown in the feed and counted on the contribution
 * calendar. Blog posts are the first source; gym sessions and GitHub activity
 * slot in later by producing more entries of their own type.
 */
export type ActivityType = "blog" | "gym" | "github";

/** All activity types, in the order they're shown in filters and legends. */
export const ACTIVITY_TYPES: readonly ActivityType[] = ["blog", "gym", "github"];

/** Short, human-readable label per activity type. */
export const ACTIVITY_TYPE_LABELS: Record<ActivityType, string> = {
  blog: "Blog",
  gym: "Gym",
  github: "GitHub",
};

export interface ActivityEntry {
  /** Local calendar date, YYYY-MM-DD (matches ContributionDay.date). */
  date: string;
  type: ActivityType;
  title: string;
  /** In-app route ("/blog/x") or external URL; omitted when not linkable. */
  url?: string;
}

/**
 * An AI-written summary of one day's GitHub work, generated by portfolio-api
 * after the day closes. One per day rather than per entry, so it sits beside
 * the entries instead of adding to the calendar's counts.
 */
export interface GitHubDaySummary {
  /** UTC calendar date, YYYY-MM-DD — the same day boundary as the entries. */
  date: string;
  /** Plain-text paragraph describing what was done. */
  summary: string;
  /** Repositories the day's work touched, busiest first. */
  repos: string[];
}

/**
 * Collapse entries into per-day counts for the calendar grid — one count per
 * entry on its date. Concatenate several sources' entries and pass the result
 * straight through; buildCalendarModel also sums any dates that overlap.
 */
export function activityToContributions(
  entries: ActivityEntry[],
): ContributionDay[] {
  const counts = new Map<string, number>();
  for (const entry of entries) {
    if (!entry?.date) {
      continue;
    }
    counts.set(entry.date, (counts.get(entry.date) ?? 0) + 1);
  }
  return Array.from(counts, ([date, count]) => ({ date, count }));
}
